### PR TITLE
Pythonify bitstamp. Fix Nonce incrementing.

### PR DESCRIPTION
**Pull request by pjz**
The Nonce incrementing fixes a bug.

Also minor pythonifications.

### CODE REVIEW

**Comment by pjz** [comment]
...these failures don't look to be related to anything I changed.  Any suggestions?

**Comment by gbeced** [comment]
Could you please elaborate on the fix to the nonce incrementing code ? What is the bug that you're fixing ? Thanks

**Comment by pjz** [comment]
Consider the case of taking three actions in the same second.  if `ret ==1` on three calls:

  * The first call sets `__prevNonce` to 1 and return 1
  * The second call sets `__prevNonce` to 2 and returns 2
  * The third call sets `__prevNonce1` to 1 (!) and returns  1

This is clearly not the desired behavior, and will cause bitstamp to reject that third action.  Looking back, I seem to have fixed it two ways:
  * use a more precise time as a nonce
  * increment based on `__prevNonce` not on the time

The first may fail if the system clock is imprecise.  The second should always work, but without the first may result in nonces far ahead of `time.time()`...not that that really matters, I suppose, unless the program gets restarted fast enough that losing track of `prevNonce` causes a collision.

**Comment by gbeced** [comment]
I see the bug, so first of all thanks for the report.

Having said that, your version is bugged as well. If getNonce is called 3 times in the same second the third result also gets back to the first one. Assume that time.time() returns 1, then your version yields:
* 100
* 101
* 100

I'll fix the current implementation with something like this:
```
class NonceGenerator(object):
    def __init__(self):
        self.__prev = None

    def getNext(self):
        ret = int(time.time())
        if self.__prev is not None and ret <= self.__prev:
            ret = self.__prev + 1
        self.__prev = ret
        return ret
```

**Comment by gbeced** [comment]
With respect to the first changes to livebroker.py, I believe that you're actually sorting the trades in ascending order, so the older trades are at the end:

```
sorted([3, 2, 1]) -> [1, 2, 3]
```

Am i missing something ?

**Comment by pjz** [comment]
Newer timestamps are larger, so ascending order is  'older trades first's.

**Comment by pjz** [comment]
Re: nonce incrementing, you're correct; I must be being saved by the extra precision.

**Comment by pjz** [comment]
Of course the sort is by I'd, not timestamp, but he reasoning holds.

**Comment by gbeced** [comment]
You're right.

So, I will only be merging the changes to _getNewTrades, but not because of the 'pythonifications', but because they fix a potential bug: If getUserTransactions stops returning the trades in descending order (newer trades first) then the call to reverse() won't yield a list in ascending order. Callers to _getNewTrades rely on the order, so explicitly sorting is safer.

The rest of the changes:
* Don't actually fix the bug, as in _getNonce.
* Are just a matter of style. In the case of _onUserTrades, 2 lookups are used instead of 1.

**Comment by pjz** [comment]
`if len(foo)` is better as `if foo` because it just has to check nonzero, not actually compute the length.

**Comment by pjz** [comment]
And the `repr` is useful for debugging.

**Comment by gbeced** [comment]
I'm sorry, but did you mean that ```if len(foo)``` is better ? or the other way around ?

**Comment by gbeced** [comment]
I understand that len(list) is O(1).

```
GabrielsMacBook:pyalgotrade gabo$ python -m timeit -s "bool(len([1, 2, 3]))"
10000000 loops, best of 3: 0.0197 usec per loop
GabrielsMacBook:pyalgotrade gabo$ python -m timeit -s "bool([1, 2, 3])"
10000000 loops, best of 3: 0.0197 usec per loop
```

**Comment by pjz** [comment]
I guess it's just stylistic then.

**Pull request closed without merging**
