### PR TITLE
Update: Add setShares method for back-testing broker

### PR DESCRIPTION
**Pull request by winkidney**
Hi, 
Nice to see you, gbeced!
Thanks for you great project which helps me work faster.

Sometimes we need to give the man some initial "btc" to do the trade, not only the cash.
So I made this PR : )

Best Regards,
winkidney

### CODE REVIEW

**Comment by winkidney** [comment]
I wonder why my ci failed : )
Because my case "testSetShares" successed, the others failed.
Would help me to figure out what is the problem?

**Comment by gbeced** [comment]
The problem with this simple approach is that is breaks existing returns analyzer because the shares set don't have an associated price, and it looks like you earned money out of nothing, and incorrect returns are calculated.

**Comment by gbeced** [comment]
Merged in d1d28ec0d2234c4f300b8d0d1e68d98f88819203

**Comment by winkidney** [comment]
@gbeced thanks for your response and fix of my commits : ), I haven't noticed that you have already make response to me, sorry for it.

**Comment by gbeced** [comment]
I gave you credit in the changelog: https://github.com/gbeced/pyalgotrade/commit/4b515d525e941fde0076fd46aff6b7525a7399c8

**Comment by winkidney** [comment]
awesome : )

**Pull request closed without merging**
